---
title: "Contributing Guide"
author: |
  Christopher Mulya  
  Natalie Coutinho  
  Pranav Kumar Mahesh
  
date: "2024-02-09"

output: html_document
---

# Contributing to DashKick Analytics

Thank you for considering contributing to DashKick Analytics! Your participation is essential for the growth and improvement of our project.

## Getting Started

1. **Fork the Repository:**
   - Fork the DashKick Analytics repository to your GitHub account.

2. **Clone the Repository:**
   - Clone your forked repository to your local machine using `git clone`.

3. **Install Dependencies:**
   - Make sure to install any project dependencies. Check the [README](https://github.com/nccoutinho/DashKick_Analytics/blob/main/README.md) for guidance.

4. **Create a Branch:**
   - Create a new branch for your contribution using `git checkout -b feature/my-feature`.

## Making Changes

1. **Code Conventions:**
   - Follow the project's coding conventions. 

2. **Commit Changes:**
   - Commit your changes with clear, concise messages. 

3. **Test Your Changes:**
   - Ensure that your changes pass existing tests and consider adding new tests if applicable.

## Submitting Changes

1. **Push Changes:**
   - Push your changes to your forked repository with `git push origin feature/my-feature`.

2. **Create a Pull Request:**
   - Open a pull request from your branch to the `main` branch of the DashKick Analytics repository.

3. **Describe Your Changes:**
   - Provide a clear and detailed description of your changes in the pull request.

## Code Review

1. **Feedback:**
   - Be open to feedback and address any comments or suggestions made during the code review process.

2. **Continuous Improvement:**
   - Use the feedback received to improve your code and contribute to the overall quality of the project.

## Thank You

Thank you for contributing to DashKick Analytics! Your efforts help us create a better tool for football analytics enthusiasts. If you have any questions, feel free to reach out to the maintainers.

Happy coding!
