# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R Package Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        r-version: [4.1.0]

    env:
      R_VERSION: ${{ matrix.r-version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ env.R_VERSION }}

    - name: Install system dependencies
      run: sudo apt-get install libcurl4-openssl-dev
  
    - name: Print Working Directory
      run: pwd
      
    - name: Set up package
      run: |
        R -e "install.packages(c('testthat', 'devtools'), repos='https://cloud.r-project.org/')"
        R -e "library(devtools)"
        R -e "devtools::install_github('ricardo-bion/ggradar', dependencies = TRUE)"

    - name: Print Library Path
      run: R -e ".libPaths()"

    - name: List Contents of Library Directory
      run: ls -R /home/runner/work/_temp/Library
      
    - name: Print Installed Packages
      run: R -e "installed.packages()"
    
    - name: Run tests
      run: Rscript test_dashkickAnalytics.R

